find . -regex './.*\.aux' -type f -delete
find . -regex './.*\.gz' -type f -delete
find . -regex './.*\.loc' -type f -delete
find . -regex './.*\.*~' -type f -delete
find . -regex './.*\.toc' -type f -delete
find . -regex './.*\.lof' -type f -delete
find . -regex './.*\.log' -type f -delete
find . -regex './.*\_latexmk' -type f -delete
find . -regex './.*\.nlo' -type f -delete
find . -regex './.*\.out' -type f -delete
find . -regex './.*\.fls' -type f -delete
